version: "3.4"
name: 'todo-list-app'
services:
  app:
    image: node:20-alpine
    entrypoint: /bin/sh
    ports:
      - 8000:8000
      - 3000:3000
    working_dir: /srv/app
    volumes:
      - type: bind
        source: ./
        target: /srv/app
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
