version: "3.4"
name: 'todo-list-app'
services:
  vite_docker:
    image: node:20-alpine
    container_name: 'quasar-app'
    entrypoint: /bin/sh
    ports:
      - 8000:8000
      - 80:3000
    working_dir: /srv/app
    volumes:
      - type: bind
        source: ./
        target: /srv/app
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
